### ISSUE TITLE
Converting NBT to JSON in NPC Holograms

### ISSUE THREAD

**Issue by Jannick05** [Pyrbu/ZNPCsPlus#134] opened 2024-03-03 21:23 UTC
When a Save is called and NPCs with a PlayerHead in their Hologram, this error occurs.

```
[22:16:36] [Thread-53/ERROR]: [YamlStorage] Failed to save npc with id 1
[22:16:36] [Thread-53/WARN]: java.lang.IllegalStateException: Failed to convert NBT to JSON.
[22:16:36] [Thread-53/WARN]:     at ZNPCsPlus-2.0.0-SNAPSHOT.jar//lol.pyr.znpcsplus.libraries.packetevents.api.protocol.nbt.codec.NBTCodec.nbtToJson(NBTCodec.java:145)
[22:16:36] [Thread-53/WARN]:     at ZNPCsPlus-2.0.0-SNAPSHOT.jar//lol.pyr.znpcsplus.libraries.packetevents.api.protocol.nbt.codec.NBTCodec.nbtToJson(NBTCodec.java:139)
[22:16:36] [Thread-53/WARN]:     at ZNPCsPlus-2.0.0-SNAPSHOT.jar//lol.pyr.znpcsplus.libraries.packetevents.api.protocol.nbt.codec.NBTCodec.nbtToJson(NBTCodec.java:139)
[22:16:36] [Thread-53/WARN]:     at ZNPCsPlus-2.0.0-SNAPSHOT.jar//lol.pyr.znpcsplus.hologram.HologramItem.serialize(HologramItem.java:109)
[22:16:36] [Thread-53/WARN]:     at ZNPCsPlus-2.0.0-SNAPSHOT.jar//lol.pyr.znpcsplus.hologram.HologramImpl.getLine(HologramImpl.java:80)
[22:16:36] [Thread-53/WARN]:     at ZNPCsPlus-2.0.0-SNAPSHOT.jar//lol.pyr.znpcsplus.storage.yaml.YamlStorage.saveNpcs(YamlStorage.java:134)
[22:16:36] [Thread-53/WARN]:     at ZNPCsPlus-2.0.0-SNAPSHOT.jar//lol.pyr.znpcsplus.npc.NpcRegistryImpl.save(NpcRegistryImpl.java:84)
[22:16:36] [Thread-53/WARN]:     at ZNPCsPlus-2.0.0-SNAPSHOT.jar//lol.pyr.znpcsplus.commands.storage.SaveAllCommand.lambda$run$0(SaveAllCommand.java:24)
[22:16:36] [Thread-53/WARN]:     at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[22:16:36] [Thread-53/WARN]:     at java.base/java.lang.Thread.run(Thread.java:1583)
[22:16:36] [Thread-53/ERROR]: [YamlStorage] Failed to save npc with id 2
[22:16:36] [Thread-53/WARN]: java.lang.IllegalStateException: Failed to convert NBT to JSON.
[22:16:36] [Thread-53/WARN]:     at ZNPCsPlus-2.0.0-SNAPSHOT.jar//lol.pyr.znpcsplus.libraries.packetevents.api.protocol.nbt.codec.NBTCodec.nbtToJson(NBTCodec.java:145)
[22:16:36] [Thread-53/WARN]:     at ZNPCsPlus-2.0.0-SNAPSHOT.jar//lol.pyr.znpcsplus.libraries.packetevents.api.protocol.nbt.codec.NBTCodec.nbtToJson(NBTCodec.java:139)
[22:16:36] [Thread-53/WARN]:     at ZNPCsPlus-2.0.0-SNAPSHOT.jar//lol.pyr.znpcsplus.libraries.packetevents.api.protocol.nbt.codec.NBTCodec.nbtToJson(NBTCodec.java:139)
[22:16:36] [Thread-53/WARN]:     at ZNPCsPlus-2.0.0-SNAPSHOT.jar//lol.pyr.znpcsplus.hologram.HologramItem.serialize(HologramItem.java:109)
[22:16:36] [Thread-53/WARN]:     at ZNPCsPlus-2.0.0-SNAPSHOT.jar//lol.pyr.znpcsplus.hologram.HologramImpl.getLine(HologramImpl.java:80)
[22:16:36] [Thread-53/WARN]:     at ZNPCsPlus-2.0.0-SNAPSHOT.jar//lol.pyr.znpcsplus.storage.yaml.YamlStorage.saveNpcs(YamlStorage.java:134)
[22:16:36] [Thread-53/WARN]:     at ZNPCsPlus-2.0.0-SNAPSHOT.jar//lol.pyr.znpcsplus.npc.NpcRegistryImpl.save(NpcRegistryImpl.java:84)
[22:16:36] [Thread-53/WARN]:     at ZNPCsPlus-2.0.0-SNAPSHOT.jar//lol.pyr.znpcsplus.commands.storage.SaveAllCommand.lambda$run$0(SaveAllCommand.java:24)
[22:16:36] [Thread-53/WARN]:     at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[22:16:36] [Thread-53/WARN]:     at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by Pyrbu** [comment] 2024-03-19 13:03
Duplicate of #132

**Closed as completed by Pyrbu** 2024-03-19 13:03 UTC
