### ISSUE TITLE
Folia error on join & Invisible NPC issue

### ISSUE THREAD

**Issue by DarkyG2** [Pyrbu/ZNPCsPlus#148] opened 2024-08-18 15:31 UTC
Hey I've stresstested my server and I got zNPCPlus outputting this error: https://pastebin.com/U66mgPLG and sometimes the NPCS will be invisible for some players where they have to either change world and comeback or log off and log back in

I'm on folia 1.20.4 Java 21

I'm on the latest build 2.0.0-SNAPSHOT

**Comment by Pyrbu** [comment] 2024-09-05 12:44
The exception you sent should be fixed by 9304c9672332598610ee9b7545e79178fe085cc1 however I'm not 100% sure that the NPCs being invisible was being caused by it so if you encounter any more issues please open another issue

**Closed as completed by Pyrbu** 2024-09-05 12:44 UTC
