### ISSUE TITLE
Add compatibility with MEG3/MEG4/ITEMSADDER/CUSTOMMODELDATA

### ISSUE THREAD

**Issue by Wxlter-Mewe** [Pyrbu/ZNPCsPlus#152] opened 2024-09-02 03:29 UTC
Hello!

Several of us know that there are other plugins that spend a lot of resources literally, they take up a lot of resources, so we have decided to use zNPCS+ for its ease of use and the light resources it spends.

I have seen several people still using those heavy plugins just for the 3d modes.

I suggest that you implement model compatibility with the plugins; ItemsAdder, Model Engine 3 and Model Engine 4, Custom Model Data.

**Comment by Pyrbu** [comment] 2024-09-05 12:49
Duplicate of #45, the reason for this not being added yet is that those plugins use real entities for everything so adding "support" for those plugins would mean basically fully recreating them. Also you can already use custom model data by using the equipment and invisibility properties with for example an armor stand.

**Closed as completed by Pyrbu** 2024-09-05 12:49 UTC
