### ISSUE TITLE
Cannot invoke "java.util.UUID.getMostSignificantBits()" because "uuid" is null

### ISSUE THREAD

**Issue by kforbro** [Pyrbu/ZNPCsPlus#60] opened 2023-06-06 11:17 UTC
Reopen #59.

I compiled a new version, but the players are still kicking from the server if the NPC PLAYER is nearby.

There is no such error with ZNPCsPlus 1.0.7. So I think the problem appeared in the commit [96e2edb](https://github.com/Pyrbu/ZNPCsPlus/commit/96e2edb13c8e7087c0b91fc80153629495e0c462)

**Comment by Pyrbu** [comment] 2023-06-16 10:49
I honestly have no clue why this is happening, I tried looking into it further and found nothing. 
Since the issue isn't present in the 2.0.0 dev builds this is most likely a won't fix

**Closed** 2023-06-16 10:49 UTC
Labels: wontfix
